### ISSUE TITLE
Core Web Vitals Tech Report missing country level data for September

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/dataform#23]
It's been rerun now, but [the query](https://github.com/HTTPArchive/dataform/blob/main/definitions/output/core_web_vitals/technologies.js) needs the following:
- HTTP Archive data
- CrUX device summary (`'chrome-ux-report', 'materialized', 'device_summary'`)
- CrUX country summary (`'chrome-ux-report', 'materialized', 'country_summary'`)

I suspect the last one of these was populated slightly later.

@max-ostapenko can check the dependencies here and add one if needed?

**Comment by tunetheweb** [comment]
Hmmm looks like it IS already specified:

https://github.com/HTTPArchive/dataform/blob/main/definitions/sources/declares.js

So confused why it failed...

**Comment by max-ostapenko** [comment]
What was the query that you ran? I have a doubt about escaped characters in regex expressions.

It's also [chrome-ux-report.materialized.country_summary](https://console.cloud.google.com/bigquery?ws=!1m5!1m4!4m3!1schrome-ux-report!2smaterialized!3scountry_summary) was last modified one hour after our query ran.
I could add an assert to check for N distinct geo values.

**Comment by tunetheweb** [comment]
I ran this for September: https://github.com/HTTPArchive/cwv-tech-report/blob/main/sql/monthly.sql

(Well, I removed the `INSERT INTO` line, rand the rest, checked it can country data, then deleted the old data and selected from that temp table to put it back in, but close enough).

@powdercloud could you help with the timing of populating these tables?:

- CrUX device summary (`'chrome-ux-report', 'materialized', 'device_summary'`)
- CrUX country summary (`'chrome-ux-report', 'materialized', 'country_summary'`)

We've automated a report when they are both available but looks like we missed most (all?) of the country level data.

Did we have to rerun that this month as part of the CrUX release? Or does it just generate slowly, a country at a time? We were assuming it was atomic for a date but maybe that is a false assumption.

**Comment by max-ostapenko** [comment]
The queries look identical.

Would be great to learn a bit more about the CrUX jobs schedule.

**Comment by powdercloud** [comment]
This month I did have to restart the release script a few times, since we removed FID from the detailed tables. I don't think I messed with device_summary or country_summary specifically though. If you see something wrong with these tables, please point it out, perhaps it's fixable.

I think generally, automating based on whether device_summary and country_summary have entries for that date may work in most cases in practice, but it would be "safer" to wait for the release announcement on our mailinglist. But, you probably realize that. :-)

**Comment by max-ostapenko** [comment]
As we discussed on the monthly call `chrome-ux-report.materialized.origin_summary` is being populated last in the CrUX pipeline.

So we should adjust the schedule on our side to run:
- on second Tuesday of the month
- when materialized.country_summary and materialized.device_summary have at least 20M rows
- last modified date of materialized.origin_summary was in this month and later than last scheduled time

@powdercloud Please share a link to the mailing list for me
