### ISSUE TITLE
Add HTTP Archive to the public datasets in BigQuery

### ISSUE THREAD

**Issue by RReverser** [HTTPArchive/dataform#26]
The new experimental UI of BigQuery doesn't seem to allow adding external sources, unless they're part of either the organisation or the catalogue of [public datasets](https://cloud.google.com/bigquery/public-data).

While, for now, it's possible to switch to the old/stable UI and so use `httparchive` from BigQuery, we should look into adding HTTPArchive to public datasets to make it accessible in the future too.

**Comment by max-ostapenko** [comment]
Can now find it on Analytics Hub
https://console.cloud.google.com/bigquery/analytics-hub/discovery/projects/httparchive/locations/us/dataExchanges/httparchive/listings/crawl
